package game;

import mainmenu.User;
import java.awt.Image;
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import mainmenu.MainMenuWindow;

public final class StoreWindowFrame extends javax.swing.JFrame {

    // attributes of a StoreWindowFrame object
    private final MainMenuWindow mainWindow;
    private int currentIndex;
    private final User currentUser;
    private final Store currentStore;

    /**
     * Creates new form StoreWindowFrame
     * @param mainWindow
     */
    public StoreWindowFrame(MainMenuWindow mainWindow) {
        initComponents();

        this.mainWindow = mainWindow;
        this.currentStore = mainWindow.getCurrentStore().clone();
        System.out.println(currentStore);
        currentStore.sortStoreItems();
        System.out.println(currentStore);
        
        final Rectangle bounds = mainWindow.getBounds();
        this.setLocation(bounds.x, bounds.y);

        currentIndex = 0;
        currentUser = mainWindow.getCurrentUser();

        updateStatus();
        loadSpecificSprite();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prevBtn = new javax.swing.JToggleButton();
        nextBtn = new javax.swing.JToggleButton();
        buyBtn = new javax.swing.JToggleButton();
        leaveBtn = new javax.swing.JToggleButton();
        imageLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        defaultSpriteButton = new javax.swing.JToggleButton();
        costTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prevBtn.setText("Previous Sprite");
        prevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBtnActionPerformed(evt);
            }
        });

        nextBtn.setText("Next Sprite");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        buyBtn.setText("Buy");
        buyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBtnActionPerformed(evt);
            }
        });

        leaveBtn.setText("Return");
        leaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveBtnActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        titleLabel.setText("Store");

        defaultSpriteButton.setText("Set as Default Sprite");
        defaultSpriteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultSpriteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(defaultSpriteButton)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(150, 150, 150)
                        .addComponent(leaveBtn)
                        .addGap(41, 41, 41))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(prevBtn)
                        .addGap(46, 46, 46)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(leaveBtn)
                        .addGap(147, 147, 147)
                        .addComponent(nextBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleLabel)
                                .addGap(18, 18, 18)
                                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(prevBtn)))))
                .addGap(29, 29, 29)
                .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultSpriteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtnActionPerformed
        currentIndex--;
        if (currentIndex < 0) {
            currentIndex = currentStore.getStoreItems().size() - 1;
        }
        updateStatus();
        loadSpecificSprite();
    }//GEN-LAST:event_prevBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        currentIndex++;
        if (currentIndex > currentStore.getStoreItems().size() - 1) {
            currentIndex = 0;
        }
        updateStatus();
        loadSpecificSprite();
    }//GEN-LAST:event_nextBtnActionPerformed

    private void leaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveBtnActionPerformed
        this.setVisible(false);
        Rectangle bounds = this.getBounds();
        mainWindow.setLocation(bounds.x, bounds.y);
        mainWindow.setVisible(true);
    }//GEN-LAST:event_leaveBtnActionPerformed

    private void buyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBtnActionPerformed
        currentStore.makePurchase(currentIndex, currentUser);
        buyBtn.setEnabled(false);
        buyBtn.setText("Purchased");
        defaultSpriteButton.setText("Set as Default Sprite");
        defaultSpriteButton.setEnabled(true);        
        if (currentStore.getSpecificStoreItem(currentIndex).equals(currentUser.getDefaultSprite())) {
            defaultSpriteButton.setEnabled(false);
            defaultSpriteButton.setText("Is Default Sprite");
        }
        mainWindow.updateLabels();
    }//GEN-LAST:event_buyBtnActionPerformed

    private void defaultSpriteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultSpriteButtonActionPerformed
        currentUser.setDefaultSprite(currentStore.getSpecificStoreItem(currentIndex));
        defaultSpriteButton.setText("Is Default Sprite");
    }//GEN-LAST:event_defaultSpriteButtonActionPerformed

    public void loadSpecificSprite() {
        imageLabel.setIcon(scaleImage(currentStore.getSpecificStoreItem(currentIndex).getSpriteCharacter()));
    }

    public ImageIcon scaleImage(ImageIcon imageToBeScaled) {
        Image scaledImg = imageToBeScaled.getImage();
        scaledImg = scaledImg.getScaledInstance(imageToBeScaled.getIconWidth()*7, imageToBeScaled.getIconHeight()*7,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        return new ImageIcon(scaledImg);
    }
    
    public void updateStatus() {
        // sets the text of the cost
        costTextField.setText("Cost: " + currentStore.getSpecificStoreItem(currentIndex).getCostToPurchase());
        
        // if the sprite is purchased
        if (userHasCurrentSprite()) {
            // disables the button
            buyBtn.setEnabled(false); 
            buyBtn.setText("Purchased");
            defaultSpriteButton.setEnabled(true);
            if (currentStore.getSpecificStoreItem(currentIndex).equals(currentUser.getDefaultSprite())) {
                defaultSpriteButton.setText("Is Default Sprite");
            } else {
                defaultSpriteButton.setText("Set as Default Sprite");
            }
        } else {  // if the sprite isn't purchased
            defaultSpriteButton.setEnabled(false);
            if (currentUser.getCurrencyPossessed() >= currentStore.getSpecificStoreItem(currentIndex).getCostToPurchase()) {
                buyBtn.setEnabled(true);
                buyBtn.setText("Buy");
                defaultSpriteButton.setText("N/A");
            } else {
                buyBtn.setEnabled(false);
                buyBtn.setText("Insufficient Funds"); //Displays the cost of the sprite
                defaultSpriteButton.setText("N/A");
            }
        }
    }
    
    private boolean userHasCurrentSprite() {
        for (Sprite currentSprite: currentUser.getSprites()) {
            if (currentSprite.equals(currentStore.getSpecificStoreItem(currentIndex))) {
                return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buyBtn;
    private javax.swing.JTextField costTextField;
    private javax.swing.JToggleButton defaultSpriteButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JToggleButton leaveBtn;
    private javax.swing.JToggleButton nextBtn;
    private javax.swing.JToggleButton prevBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}