package game;

import adventurerush.User;
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import mainmenu.MainMenuWindow;

public final class StoreWindowFrame extends javax.swing.JFrame {

    // attributes of a StoreWindowFrame object
    private final MainMenuWindow mainWindow;
    private int currentIndex;
    private final User currentUser;
    private final Store currentStore;

    /**
     * Creates new form StoreWindowFrame
     * @param mainWindow
     */
    public StoreWindowFrame(MainMenuWindow mainWindow) {
        initComponents();

        this.mainWindow = mainWindow;
        this.currentStore = mainWindow.getCurrentStore().clone();

        final Rectangle bounds = mainWindow.getBounds();
        this.setLocation(bounds.x, bounds.y);

        currentIndex = 0;
        currentUser = mainWindow.getCurrentUser();

        updateStatus();
        loadSpecificSprite();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prevBtn = new javax.swing.JToggleButton();
        nextBtn = new javax.swing.JToggleButton();
        buyBtn = new javax.swing.JToggleButton();
        leaveBtn = new javax.swing.JToggleButton();
        lblTitle = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prevBtn.setText("Previous Sprite");
        prevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBtnActionPerformed(evt);
            }
        });

        nextBtn.setText("Next Sprite");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        buyBtn.setText("Buy");
        buyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBtnActionPerformed(evt);
            }
        });

        leaveBtn.setText("Leave Store");
        leaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveBtnActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        lblTitle.setText("Store");

        lblCost.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblCost.setText("Cost:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prevBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(leaveBtn)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblCost)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(buyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(lblTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(leaveBtn)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prevBtn)
                                .addGap(57, 57, 57)
                                .addComponent(nextBtn)
                                .addGap(82, 82, 82))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(lblCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addGap(217, 313, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)))))
                .addComponent(buyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtnActionPerformed
        currentIndex--;
        if (currentIndex < 0) {
            currentIndex = currentStore.getStoreItems().size() - 1;
        }
        updateStatus();
        loadSpecificSprite();
    }//GEN-LAST:event_prevBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        currentIndex++;
        if (currentIndex > currentStore.getStoreItems().size() - 1) {
            currentIndex = 0;
        }
        updateStatus();
        loadSpecificSprite();
    }//GEN-LAST:event_nextBtnActionPerformed

    private void leaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveBtnActionPerformed
        this.setVisible(false);
        mainWindow.setVisible(true);
    }//GEN-LAST:event_leaveBtnActionPerformed

    private void buyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBtnActionPerformed
        currentUser.setCurrencyPossessed(currentUser.getCurrencyPossessed() - currentStore.getSpecificStoreItem(currentIndex).getCostToPurchase());
        currentUser.addSprite(currentStore.getSpecificStoreItem(currentIndex));
    }//GEN-LAST:event_buyBtnActionPerformed

    public void loadSpecificSprite() {
        lblImage.setIcon(new ImageIcon(currentStore.getSpecificStoreItem(currentIndex).getFilePath()));
    }

    public void updateStatus() {
        // sets the text of the cost
        lblCost.setText("Cost: " + currentStore.getSpecificStoreItem(currentIndex).getCostToPurchase());

        // if the sprite is purchased
        if (userHasCurrentSprite()) {
            // disables the button
            buyBtn.setEnabled(false); 
            buyBtn.setText("Purchased");
        } else {  // if the sprite isn't purchased
            if (currentUser.getCurrencyPossessed() < currentStore.getSpecificStoreItem(currentIndex).getCostToPurchase()) {
                buyBtn.setEnabled(false);
                buyBtn.setText("sus");
            } else {
                buyBtn.setEnabled(true);
                buyBtn.setText(Integer.toString(currentStore.getSpecificStoreItem(currentIndex).getCostToPurchase())); //Displays the cost of the sprite
            }
            // display cost to user in a label on the right side of the screen 
            // lblCost.setText(lblCost.substring(lblCost.contains(":') + 1) + Integer.toString(currentStore.getSpecificStoreItem(currentIndex).getCostToPurchase()));
        }
    }
    
    private boolean userHasCurrentSprite() {
        for (Sprite currentSprite: currentUser.getSprites()) {
            if (currentSprite.equals(currentStore.getSpecificStoreItem(currentIndex))) {
                return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buyBtn;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JToggleButton leaveBtn;
    private javax.swing.JToggleButton nextBtn;
    private javax.swing.JToggleButton prevBtn;
    // End of variables declaration//GEN-END:variables

}
